### PR TITLE
5 урок

### PR DESCRIPTION
**Pull request by vefivjriej**
done.

### CODE REVIEW

**Comment by vefivjriej** [comment]
Зинин Захар

**Comment by Slava-ne-Merlow** [comment]
...

**Comment by Slava-ne-Merlow** [comment]
Cоси

**Comment by Monax111** [comment]
Instantiation of [simple type, class ru.tbank.education.school.ru.tbank.education.school.lesson5.Person2] value failed for JSON property firstName due to missing (therefore NULL) value for creator parameter firstName which is a non-nullable type
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 145] (through reference chain: ru.tbank.education.school.ru.tbank.education.school.lesson5.Person2["firstName"])

**Comment by Monax111** [comment]
тесты не проходят. Не принятно

**Pull request closed without merging**
